spring:
  datasource:
    url: ${DEMO_DB_URL}
    username: ${DEMO_DB_USERNAME}
    password: ${DEMO_DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080